global:
  constants:
    min_transform_licks_cutoff: 0.00001
    max_med_duration_cutoff: 13
    max_events_cutoff: 150
  params:
    # Full parameter list with two-well defaults (Parameters.two_well()).
    baseline_window_minutes: 3
    feeding_threshold: 10
    feeding_minimum: 10
    tasting_minimum: 0
    tasting_maximum: 10
    feeding_minevents: 1
    tasting_minevents: 1
    samples_per_second: 5
    feeding_event_link_gap: 5
    chamber_size: 2  
    correct_for_dual_feeding: false
    pi_direction: left
  experimental_design_factors:
    paired: [Paired, Unpaired]
    genotype: [Chrim, WCS]
  well_names:
    A: Sucrose
    B: Yeast

dfms:
  1:
    params:      
      pi_direction: left    
    chambers:
      1: Paired,WCS 
      2: Unpaired,WCS
      3: Paired,Chrim
      4: Unpaired,Chrim
      5: Paired,Chrim
      6: Unpaired,Chrim
  2:
    params:      
      pi_direction: left
    chambers:
      1: Unpaired,WCS
      2: Paired,WCS
      3: Unpaired,Chrim
      4: Paired,Chrim
      5: Unpaired,Chrim
      6: Paired,Chrim
  3:
    params:      
      pi_direction: right
    chambers:
      1: Paired,WCS
      2: Unpaired,WCS
      3: Paired,Chrim
      4: Unpaired,Chrim
      5: Paired,Chrim
      6: Unpaired,Chrim
  4:
    params:      
      pi_direction: right
    chambers:
      1: Unpaired,WCS
      2: Paired,WCS
      3: Unpaired,Chrim
      4: Paired,Chrim
      5: Unpaired,Chrim
      6: Paired,Chrim
  5 :
    params:      
      pi_direction: left
    chambers:
      1: Paired,Chrim
      2: Unpaired,Chrim
      3: Paired,WCS
      4: Unpaired,WCS
      5: Paired,WCS
      6: Unpaired,WCS
  6:
    params:      
      pi_direction: left
    chambers:
      1: Unpaired,Chrim
      2: Paired,Chrim
      3: Unpaired,WCS
      4: Paired,WCS
      5: Unpaired,WCS
      6: Paired,WCS
  7:
    params:      
      pi_direction: right
    chambers:
      1: Paired,Chrim
      2: Unpaired,Chrim
      3: Paired,WCS
      4: Unpaired,WCS
      5: Paired,WCS
      6: Unpaired,WCS
  8:
    params:      
      pi_direction: right
    chambers:
      1: Unpaired,Chrim
      2: Paired,Chrim
      3: Unpaired,WCS
      4: Paired,WCS
      5: Unpaired,WCS
      6: Paired,WCS